In [1]:
import torch

### norm

In [2]:
a = torch.full([8], 1)
b = a.view(2,4)
c = a.view(2,2,2)

In [3]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [5]:
a.norm(1), b.norm(1), c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [6]:
a.norm(2), b.norm(2), c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [7]:
b.norm(1, dim=1)

tensor([4., 4.])

In [8]:
b.norm(2, dim=1)

tensor([2., 2.])

In [9]:
c.norm(1, dim=0)

tensor([[2., 2.],
        [2., 2.]])

In [10]:
c.norm(2, dim=0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

### mean, sum, min, max, prod

In [11]:
a = torch.arange(8).view(2,4).float()
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [12]:
a.min(), a.max(), a.mean(), a.prod()

(tensor(0.), tensor(7.), tensor(3.5000), tensor(0.))

In [13]:
a.sum()

tensor(28.)

In [14]:
a.argmax(), a.argmin()

(tensor(7), tensor(0))

In [15]:
a = torch.randn(4,10)
a[0]

tensor([ 0.2540,  1.1653,  1.7702,  1.0743, -0.4121,  0.3516,  1.8466,  0.6909,
         0.0996,  0.3038])

In [16]:
a.argmax()

tensor(6)

In [17]:
a.argmax(dim=1)

tensor([6, 4, 3, 0])

### dim, keepdim

In [18]:
a

tensor([[ 0.2540,  1.1653,  1.7702,  1.0743, -0.4121,  0.3516,  1.8466,  0.6909,
          0.0996,  0.3038],
        [-0.0518,  0.8254, -0.4905,  0.3784,  1.2221,  0.2635,  0.9224, -0.6994,
          0.3940, -0.1270],
        [-1.0295,  0.5523,  0.4471,  1.3345,  0.8819, -2.0069, -0.2763,  0.8967,
          0.1181, -0.2533],
        [ 1.7442,  0.2174, -1.5181,  1.1899, -0.9525,  0.2414, -0.8511,  0.1549,
         -0.3737, -0.7159]])

In [19]:
a.max(dim=1)

torch.return_types.max(
values=tensor([1.8466, 1.2221, 1.3345, 1.7442]),
indices=tensor([6, 4, 3, 0]))

In [20]:
a.argmax(dim=1)

tensor([6, 4, 3, 0])

In [21]:
a.max(dim=1, keepdim=True)

torch.return_types.max(
values=tensor([[1.8466],
        [1.2221],
        [1.3345],
        [1.7442]]),
indices=tensor([[6],
        [4],
        [3],
        [0]]))

In [22]:
a.argmax(dim=1, keepdim=True)

tensor([[6],
        [4],
        [3],
        [0]])

### topk, kth

In [23]:
a.topk(3, dim=1)

torch.return_types.topk(
values=tensor([[1.8466, 1.7702, 1.1653],
        [1.2221, 0.9224, 0.8254],
        [1.3345, 0.8967, 0.8819],
        [1.7442, 1.1899, 0.2414]]),
indices=tensor([[6, 2, 1],
        [4, 6, 1],
        [3, 7, 4],
        [0, 3, 5]]))

In [24]:
a.topk(3, dim=1, largest=False)

torch.return_types.topk(
values=tensor([[-0.4121,  0.0996,  0.2540],
        [-0.6994, -0.4905, -0.1270],
        [-2.0069, -1.0295, -0.2763],
        [-1.5181, -0.9525, -0.8511]]),
indices=tensor([[4, 8, 0],
        [7, 2, 9],
        [5, 0, 6],
        [2, 4, 6]]))

In [25]:
a.kthvalue(8, dim=1, keepdim=True)

torch.return_types.kthvalue(
values=tensor([[1.1653],
        [0.8254],
        [0.8819],
        [0.2414]]),
indices=tensor([[1],
        [1],
        [4],
        [5]]))

### compare

In [26]:
a>0

tensor([[1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
        [0, 1, 0, 1, 1, 1, 1, 0, 1, 0],
        [0, 1, 1, 1, 1, 0, 0, 1, 1, 0],
        [1, 1, 0, 1, 0, 1, 0, 1, 0, 0]], dtype=torch.uint8)

In [27]:
torch.gt(a,0)

tensor([[1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
        [0, 1, 0, 1, 1, 1, 1, 0, 1, 0],
        [0, 1, 1, 1, 1, 0, 0, 1, 1, 0],
        [1, 1, 0, 1, 0, 1, 0, 1, 0, 0]], dtype=torch.uint8)

In [28]:
a != 0

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.uint8)

In [29]:
a = torch.ones(2,3)
b = torch.randn(2,3)

In [30]:
torch.eq(a,b)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [31]:
torch.equal(a,a)

True