In [1]:
import torch
import numpy as np

In [2]:
a = torch.randn(2, 3)
a.type()

'torch.FloatTensor'

In [3]:
type(a)

torch.Tensor

In [4]:
isinstance(a, torch.FloatTensor)

True

In [5]:
isinstance(a, torch.cuda.FloatTensor)

False

In [6]:
a = a.cuda()
isinstance(a, torch.cuda.FloatTensor)

True

### dim 0

In [7]:
torch.tensor(1.3)

tensor(1.3000)

In [8]:
a = torch.tensor(2.2)
a.shape

torch.Size([])

In [9]:
len(a.shape)

0

In [10]:
a.size()

torch.Size([])

### dim 1

In [11]:
torch.tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

In [12]:
torch.FloatTensor(2).shape

torch.Size([2])

In [13]:
data = np.ones(2)
data

array([1., 1.])

In [14]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

In [15]:
a = torch.ones(1)
a.shape

torch.Size([1])

### dim 2

In [16]:
a = torch.randn(2, 3)
a

tensor([[-1.0545,  1.0059,  1.4703],
        [-1.0995,  0.3736, -1.4261]])

In [17]:
a.shape

torch.Size([2, 3])

In [18]:
a.size(0)

2

In [19]:
a.shape[1]

3

### dim 3

In [20]:
a = torch.rand(1, 2, 3)
a

tensor([[[0.2661, 0.2866, 0.1413],
         [0.0406, 0.1751, 0.3077]]])

In [21]:
a.shape

torch.Size([1, 2, 3])

In [22]:
a[0]

tensor([[0.2661, 0.2866, 0.1413],
        [0.0406, 0.1751, 0.3077]])

In [23]:
list(a.shape)

[1, 2, 3]

### dim 4

In [24]:
a = torch.rand(2, 3, 28, 28)
a

tensor([[[[0.6641, 0.2864, 0.6857,  ..., 0.7823, 0.8619, 0.1815],
          [0.1917, 0.9650, 0.0313,  ..., 0.0904, 0.2687, 0.1883],
          [0.5358, 0.0711, 0.3372,  ..., 0.8311, 0.7764, 0.4785],
          ...,
          [0.7880, 0.9058, 0.6060,  ..., 0.7201, 0.6522, 0.5221],
          [0.0882, 0.6401, 0.8812,  ..., 0.3059, 0.4254, 0.5358],
          [0.6550, 0.8157, 0.9168,  ..., 0.8706, 0.7290, 0.1619]],

         [[0.9383, 0.9188, 0.2994,  ..., 0.6767, 0.0875, 0.6819],
          [0.2419, 0.9255, 0.6931,  ..., 0.8273, 0.5832, 0.9346],
          [0.6923, 0.7506, 0.9320,  ..., 0.1873, 0.5738, 0.5723],
          ...,
          [0.6404, 0.4206, 0.0478,  ..., 0.5027, 0.0387, 0.8525],
          [0.1256, 0.7951, 0.0042,  ..., 0.2060, 0.5542, 0.7196],
          [0.3270, 0.4880, 0.9567,  ..., 0.3842, 0.7960, 0.1456]],

         [[0.8511, 0.9445, 0.7036,  ..., 0.6845, 0.9976, 0.6192],
          [0.3380, 0.5152, 0.9032,  ..., 0.3576, 0.0812, 0.2736],
          [0.0224, 0.4128, 0.9843,  ..., 0

In [25]:
a.shape

torch.Size([2, 3, 28, 28])

### mixed

In [26]:
a.numel()  # number of element

4704

In [27]:
a.dim()

4