In [1]:
import torch
import numpy as np

In [2]:
a = torch.rand(4,3,28,28)

In [3]:
a[0].shape

torch.Size([3, 28, 28])

In [4]:
a[0,0].shape

torch.Size([28, 28])

In [5]:
a[0,0,2,4].shape

torch.Size([])

In [6]:
a[0,0,2,4]

tensor(0.8673)

### select first/last N

In [7]:
a.shape

torch.Size([4, 3, 28, 28])

In [8]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [9]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

In [10]:
a[:2,1:,:,:].shape

torch.Size([2, 2, 28, 28])

In [11]:
a[:2,-1:,:,:].shape

torch.Size([2, 1, 28, 28])

### select by steps

In [12]:
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

In [13]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

### select by specific index

In [14]:
a.shape

torch.Size([4, 3, 28, 28])

In [15]:
a.index_select(0, torch.tensor([0,2])).shape

torch.Size([2, 3, 28, 28])

In [16]:
a.index_select(1, torch.tensor([1,2])).shape

torch.Size([4, 2, 28, 28])

In [17]:
a.index_select(2, torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

### ...

In [18]:
a.shape

torch.Size([4, 3, 28, 28])

In [19]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [20]:
a[0,...].shape

torch.Size([3, 28, 28])

In [21]:
a[:,1,...].shape

torch.Size([4, 28, 28])

In [22]:
a[..., :2].shape

torch.Size([4, 3, 28, 2])

In [23]:
a[1:,...,:2].shape

torch.Size([3, 3, 28, 2])

### select by mask

In [24]:
x = torch.randn(3,4)
x

tensor([[-0.3308, -0.1154, -0.3783,  1.2392],
        [ 2.4635,  0.4511,  2.2857,  0.2876],
        [ 0.0929, -0.7003,  0.0505, -1.9399]])

In [25]:
mask = x.ge(0.5)
mask

tensor([[0, 0, 0, 1],
        [1, 0, 1, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)

In [26]:
torch.masked_select(x, mask)

tensor([1.2392, 2.4635, 2.2857])

In [30]:
torch.masked_select(x, mask).shape

torch.Size([3])

### select by flatten index

In [31]:
src = torch.tensor([[4,3,5],[6,7,8]])
torch.take(src, torch.tensor([0,2,5]))

tensor([4, 5, 8])