In [1]:
import torch

### view reshape(二者相同)

In [2]:
a = torch.rand(4,1,28,28)
a.shape

torch.Size([4, 1, 28, 28])

In [3]:
a.view(4,28*28)

tensor([[0.2828, 0.2351, 0.3316,  ..., 0.8599, 0.5706, 0.4370],
        [0.4511, 0.8049, 0.5556,  ..., 0.6115, 0.5590, 0.3874],
        [0.6134, 0.0013, 0.8485,  ..., 0.4639, 0.7615, 0.4531],
        [0.6107, 0.0275, 0.0192,  ..., 0.7659, 0.5813, 0.1943]])

In [4]:
a.view(4,28*28).shape

torch.Size([4, 784])

### squeeze unsqueeze

In [5]:
a.shape

torch.Size([4, 1, 28, 28])

In [6]:
a.unsqueeze(3).shape

torch.Size([4, 1, 28, 1, 28])

In [7]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [8]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [9]:
a.unsqueeze(-2).shape

torch.Size([4, 1, 28, 1, 28])

In [10]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

In [11]:
a = torch.tensor([1.2,2.3])

In [12]:
a.unsqueeze(-1)

tensor([[1.2000],
        [2.3000]])

In [13]:
a.unsqueeze(0)

tensor([[1.2000, 2.3000]])

In [14]:
b = torch.rand(32)
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)
b.shape

torch.Size([1, 32, 1, 1])

In [15]:
b.squeeze().shape

torch.Size([32])

In [16]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [17]:
b.squeeze(-1).shape

torch.Size([1, 32, 1])

In [18]:
b.squeeze(1).shape

torch.Size([1, 32, 1, 1])

In [19]:
b.squeeze(-4).shape

torch.Size([32, 1, 1])

### expand/repeat

In [20]:
a = torch.rand(4,32,14,14)
b.shape

torch.Size([1, 32, 1, 1])

In [21]:
b.expand(4,32,14,14).shape

torch.Size([4, 32, 14, 14])

In [22]:
b.expand(-1,32,-1,-1).shape

torch.Size([1, 32, 1, 1])

In [23]:
b.expand(-1,32,-1,-4).shape  # bug

torch.Size([1, 32, 1, -4])

In [24]:
b.shape

torch.Size([1, 32, 1, 1])

In [25]:
b.repeat(4,32,1,1).shape

torch.Size([4, 1024, 1, 1])

In [26]:
b.repeat(4,1,1,1).shape

torch.Size([4, 32, 1, 1])

In [27]:
b.repeat(4,1,14,14).shape  # repeat占用较多内存

torch.Size([4, 32, 14, 14])

### .t

In [28]:
a = torch.randn(3,4)
a.t()  # .t()只能用于二维矩阵

tensor([[ 1.2835,  0.5403, -1.1909],
        [-0.6827,  0.8421,  0.3210],
        [ 0.2276,  0.5199, -0.3773],
        [ 0.9786, -0.1661, -0.9760]])

### transpose

In [29]:
a = torch.randn(4,3,32,32)
a.shape

torch.Size([4, 3, 32, 32])

In [30]:
a1 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32)
a2 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,32,32,3).transpose(1,3)
a1.shape, a2.shape

(torch.Size([4, 3, 32, 32]), torch.Size([4, 3, 32, 32]))

In [31]:
torch.all(torch.eq(a,a1))  # a1扰乱了数据顺序，错误

tensor(0, dtype=torch.uint8)

In [32]:
torch.all(torch.eq(a,a2))  # a2正确

tensor(1, dtype=torch.uint8)

### permute

In [33]:
a = torch.randn(4,3,28,28)

In [34]:
a.transpose(1,3).shape

torch.Size([4, 28, 28, 3])

In [35]:
b = torch.randn(4,3,28,32)

In [36]:
b.transpose(1,3).shape

torch.Size([4, 32, 28, 3])

In [37]:
b.transpose(1,3).transpose(1,2).shape

torch.Size([4, 28, 32, 3])

In [38]:
b.permute(0,2,3,1).shape

torch.Size([4, 28, 32, 3])